// GENERATED by scripts/sync-data.mjs from data.json — do not edit by hand.
// Rebuild with `npm run sync:data`.
export const EMBEDDED_DATA = {
  "profile": {
    "name": "Ronit Baniya Gupta",
    "handle": "TheRowKneet",
    "role": "Computer Engineer & Builder of Things",
    "slogan": "if it doesn't exist, I will build it",
    "location": "Pokhara, Nepal",
    "phone": "+977 982-911-7277",
    "phone_raw": "+9779829117277",
    "whatsapp": "9779829117277",
    "email": "ronitbaniya68@gmail.com",
    "socials": {
      "github": "https://github.com/TheRowKneet68",
      "linkedin": "https://www.linkedin.com/in/jr-erronitbaniya/",
      "facebook": "https://www.facebook.com/TheRowKneet/",
      "instagram": "https://www.instagram.com/jr.er_ronitbaniya68"
    },
    "badges": [
      "Bachelor of Computer Engineering — Pokhara University",
      "Diploma in Computer Engineering — Batch 2020",
      "3rd DAN Black Belt — Taekwondo",
      "High-Performance Coach Trained",
      "3+ Innovation Awards"
    ],
    "stats": [
      {
        "label": "projects shipped",
        "value": "25+"
      },
      {
        "label": "awards & wins",
        "value": "10+"
      },
      {
        "label": "martial arts dan",
        "value": "3rd DAN"
      },
      {
        "label": "lines of stubbornness",
        "value": "∞"
      }
    ],
    "focus": [
      "Embedded Systems",
      "IoT & Automation",
      "Computer Vision",
      "AI & ML",
      "Robotics",
      "Hardware Design",
      "Intelligent Systems"
    ],
    "tech": {
      "languages": [
        "Python",
        "C",
        "C++",
        "Java",
        "JavaScript",
        "HTML",
        "CSS",
        "VHDL"
      ],
      "hardware": [
        "ESP32",
        "ESP8266",
        "Arduino Uno",
        "Arduino Nano",
        "nRF52840",
        "STM32"
      ],
      "sensors": [
        "MPU6050",
        "MAX30102",
        "Pulse Sensor",
        "DS18B20",
        "MLX90614",
        "Ultrasonic",
        "PIR",
        "RFID",
        "IR",
        "GPS",
        "SIM800L"
      ],
      "displays": [
        "OLED",
        "LCD I2C",
        "1.28\" Round TFT"
      ],
      "comms": [
        "HC-05",
        "HM-10",
        "NRF Modules",
        "BLE",
        "Wi-Fi",
        "MQTT"
      ],
      "power": [
        "18650",
        "TP4056",
        "Buck Converters",
        "LM2596",
        "7805",
        "Bridge Rectifiers"
      ],
      "software": [
        "Firebase",
        "Supabase",
        "React",
        "Node.js",
        "Flutter",
        "OpenCV",
        "MediaPipe",
        "PlatformIO",
        "ESP-IDF",
        "MIT App Inventor"
      ]
    },
    "principles": [
      {
        "title": "Originality over everything",
        "note": "No copy-paste ideas. If someone already made it, I make it better or I don't make it."
      },
      {
        "title": "Build it, then improve it",
        "note": "I'd rather ship a rough working thing today than a perfect thing next year."
      },
      {
        "title": "Brutally honest feedback",
        "note": "Tell me I'm wrong and why. Comforting lies never built anything."
      },
      {
        "title": "Hardware + software, together",
        "note": "The interesting problems live where the code touches real wires and real world."
      }
    ],
    "journey": [
      {
        "year": "2020",
        "title": "Started Diploma in Computer Engineering",
        "note": "Picked up an Arduino for the first time and discovered embedded systems. That single board changed the direction of my career."
      },
      {
        "year": "2021",
        "title": "Learning by Building",
        "note": "Built home automation systems, RC cars, relay circuits, IR-controlled devices, and countless small prototypes. Every failure taught me something new about hardware and software."
      },
      {
        "year": "2022",
        "title": "GRAVAS",
        "note": "Developed my first major engineering project and showcased it at the Rojgar Mela, confirming my passion for building real-world technology."
      },
      {
        "year": "2023",
        "title": "Graduated with Diploma in Computer Engineering",
        "note": "Completed the Diploma in Computer Engineering — three years of building, breaking, and rebuilding that became the foundation of everything since."
      },
      {
        "year": "2023",
        "title": "Beyond the Classroom",
        "note": "Focused on Embedded Systems, IoT, PCB design, firmware development, and hardware-software integration, transforming ideas into working prototypes."
      },
      {
        "year": "2024",
        "title": "Suraksha Ghar",
        "note": "Designed and built a complete IoT home automation ecosystem featuring custom firmware, embedded hardware, web dashboard, and mobile application — my first product built for real-world deployment."
      },
      {
        "year": "September 2024",
        "title": "Began Bachelor of Computer Engineering",
        "note": "Enrolled at Pokhara Engineering College to pursue a Bachelor of Computer Engineering while continuing to build and ship hardware projects."
      },
      {
        "year": "2025",
        "title": "A Breakthrough Year",
        "note": "February 7, 2025\n🏆 Winner — UDAAN 2025 Project Expo\n📜 Certificate of Appreciation — UDAAN 2025 Participant\nPresented Suraksha360 at IOE Paschimanchal Campus and secured the overall Winner title.\n\nFebruary 12–13, 2025\n🏆 People's Choice Award — OCTATE 2025\nReceived the Public Choice Award at the National Level Technical Festival, recognizing both technical innovation and audience impact.\n\nJune 8, 2025\n🥈 First Runner-Up — Innosphere 1.0 Hardware Project Exhibition\nRecognized among the top hardware innovations organized by the Tech Club of Pokhara University.\n\n🤝 Community Partner — Hackathon Nova\nReceived a Certificate of Appreciation for supporting Hackathon Nova through Suraksha Ghar and contributing to innovation and collaboration.\n\n🙌 Volunteer — Hackathon Nova\nRecognized for volunteering and helping organize one of the college's largest hackathons.\n\n🎖 CAPEC Leadership Recognition\nAwarded a Certificate of Appreciation for dedication, leadership, and contribution as an active member of CAPEC (Computer Association of Pokhara Engineering College).\n\nDecember 26, 2025\n📌 Appointed Joint Secretary — CAPEC\nOfficially appointed Joint Secretary for the 2026 tenure, recognizing leadership, commitment, and service to the engineering community."
      },
      {
        "year": "2026",
        "title": "Engineering at Scale",
        "note": "January 28–29, 2026 — 9th PEC Tech Expo\n🥈 First Runner-Up — Civil Project Competition\n🏅 Consolation Prize — Computer & IT Project Competition\nShowcased projects across disciplines: Suraksha360, HerLegal, RUDRA-I Rocket, Construction of Roundabout with Pedestrian Bridge at Prithvichowk, and Laser Tag.\n\n🚀 Launched the RUDRA-I experimental rocket during the expo, demonstrating its communication and recovery system in front of visitors and judges. The launch was covered by multiple local media outlets, making it one of the event's highlights.\n\nFeatured in the Media\n📰 ICT Frame — RUDRA-1 Rocket Launch: Innovation at the 9th PEC Tech Expo\n📰 WOW Magazine Nepal — Facebook Coverage\n📹 24 Ghanta Nepal — Instagram Reel\n📹 Digital Nepal — Instagram Reel\n📘 Routine of Education — Facebook Feature\n\nApril 4, 2026 — Fishtail University Fair\nPresented Suraksha360 to students, faculty, and industry visitors, demonstrating practical IoT, automation, and embedded system solutions.\n\nJune 25–26, 2026\n🏆 1st Position — GCES IT Expo\nSuraksha360 earned First Place, recognizing months of engineering, iteration, and real-world product development."
      },
      {
        "year": "2028 (Expected)",
        "title": "Bachelor of Engineering in Computer Engineering",
        "note": "Expected graduation with a Bachelor of Engineering in Computer Engineering — building toward a career where code meets wires."
      },
      {
        "year": "Present",
        "title": "Building What's Next",
        "note": "Currently developing projects including Swasthya Sathi, SwiftIgnite v2, commercial web platforms, AI-powered embedded systems, and next-generation IoT solutions while continuing to compete, innovate, and build products that solve real-world problems."
      }
    ],
    "fun_facts": [
      "3rd DAN Black Belt in Taekwondo — started BS 2070, stopped, came back, finished high-performance coach training.",
      "Weak at theory, strong at shipping. I learn better with a screwdriver in my hand.",
      "Wanted to be a teacher once. Explicitly not anymore. Building a company instead.",
      "I send cold messages to restaurants to build their websites. It works sometimes. I keep iterating."
    ],
    "about": [
      "Computer engineer from Pokhara, Nepal. I work with microcontrollers the way other people work with keyboards — and I've been at it since the first time I held an Arduino and was immediately done for.",
      "My work lives where code touches real wires: embedded systems, IoT ecosystems, computer vision and the occasional website when the pitch lands. I'd rather ship a rough working thing today than a perfect thing next year.",
      "I've taken hardware from breadboard to market — a home-automation switch with a custom PCB, a call-based motor controller that works where WiFi doesn't reach, and an emergency-response ecosystem that's swept the hackathon circuit. If it doesn't exist, I build it."
    ],
    "testimonials": [
      {
        "quote": "Took an idea that existed only in his head and turned it into a product that won across categories. He thinks in hardware and software at the same time.",
        "source": "Hackathon judge, UDAAN 2025"
      },
      {
        "quote": "The rare engineer who'll solder the PCB, flash the firmware and then fight the front-end until it looks good. Three jobs, one person.",
        "source": "College project partner"
      },
      {
        "quote": "He messaged us out of nowhere, built the site, and it genuinely made the cafe feel more professional. Cold outreach that actually delivers.",
        "source": "Restaurant client, Lakeside"
      }
    ],
    "featured_in": [
      {
        "name": "ICT Frame",
        "url": "https://ictframe.com/rudra-1-rocket-launch/"
      },
      {
        "name": "WOW Magazine Nepal",
        "url": "https://www.facebook.com/wowmagazinenepal/posts/students-of-pokhara-engineering-college-successfully-launched-an-experimental-ro/1500618618739581/"
      },
      {
        "name": "24 Ghanta Nepal",
        "url": "https://www.instagram.com/reel/DUSxwYtk5ET/?hl=en"
      },
      {
        "name": "Digital Nepal",
        "url": "https://www.instagram.com/reel/DUV38WUj5NT/"
      },
      {
        "name": "Routine of Education",
        "url": "https://www.facebook.com/share/p/1FEQQ6gvGB/"
      }
    ]
  },
  "projects": [
    {
      "id": "suraksha360",
      "title": "Suraksha360",
      "tagline": "Smart security & emergency response ecosystem",
      "category": "IoT & Security",
      "year": "2025",
      "status": "award-winning",
      "featured": true,
      "tech": [
        "ESP32",
        "Firebase",
        "IoT",
        "AI",
        "Wearables"
      ],
      "description": "My biggest ecosystem to date. Started as a home-security project and grew into a full emergency-response platform — IoT sensors, wearables, healthcare and AI stitched together. Won Best of the Best at UDAAN 2025 and swept multiple award categories.",
      "highlights": [
        "Winner — 11th GCES IT Expo",
        "Best of the Best — UDAAN 2025",
        "Multiple award categories"
      ],
      "caseStudy": {
        "problem": [
          "Home security in Nepal is mostly a door lock and a hope. Commercial systems are expensive, locked to the vendor, and fall apart the moment the internet hiccups.",
          "An alarm going off in an empty house is a loud noise, not a response. Sensors don't call anyone."
        ],
        "solution": [
          "Built it as a platform, not a product: IoT sensors, wearables, healthcare devices and an AI layer all reporting into one emergency-response flow.",
          "When a PIR trips, the system decides whether it's a real event, alerts the owner, then escalates to emergency contacts. When an elderly wearable goes still, someone gets called."
        ],
        "architecture": [
          "ESP32 nodes run firmware written in PlatformIO/ESP-IDF and report over WiFi/MQTT to a cloud layer; state lives in Firebase.",
          "Wearables measure vitals and motion, a companion app is the human interface for alerts and control.",
          "An AI layer classifies events — intrusion vs cat vs false trip — so you don't get woken by noise."
        ],
        "stack": ["ESP32", "Firebase", "MQTT", "PlatformIO", "Wearables", "AI"],
        "challenges": [
          {
            "problem": "The demo had to work live, in front of judges, over WiFi that didn't belong to me.",
            "fix": "Firmware designed to degrade gracefully — sensors kept logging locally and synced when connectivity came back. Offline-first because demos are the worst network in the world."
          },
          {
            "problem": "A security system that cries wolf gets ignored. False positives were the real enemy.",
            "fix": "Replaced single-sensor triggers with sensor fusion and simple event classification, so a curtain moving isn't an intruder."
          }
        ],
        "impact": [
          "Best of the Best at UDAAN 2025, winner at the 11th GCES IT Expo, plus multiple category awards.",
          "Proved the stack — it's the platform I keep stacking hardware onto."
        ],
        "lessons": [
          "A system that works offline in a demo is a system that works offline in an emergency. Build for the worst network first.",
          "The trophies are nice, but the point is that it could actually save someone."
        ]
      },
      "links": {
        "github": "https://github.com/TheRowKneet68"
      }
    },
    {
      "id": "swasthya-sathi",
      "title": "Swasthya Sathi",
      "tagline": "Healthcare platform with AI symptom checker",
      "category": "AI & Health",
      "year": "2025",
      "status": "in development",
      "featured": true,
      "tech": [
        "Next.js",
        "Supabase",
        "AI",
        "IoT"
      ],
      "description": "A healthcare platform I'm building — AI symptom checker, digital health records, doctor finder, emergency assistance and IoT integration. Health data in one place, connected to hardware where it counts.",
      "highlights": [
        "AI symptom checker",
        "Digital health records",
        "Emergency assistance module"
      ],
      "caseStudy": {
        "problem": [
          "Health data in Nepal is scattered across paper prescriptions, WhatsApp messages and memory. Your records follow you around inside your head.",
          "A symptom checker that just hands you a diagnosis is dangerous. It had to be a triage tool, not a doctor."
        ],
        "solution": [
          "One platform for symptoms, records, doctors and emergency assistance — with an AI checker that's honest about what it can't know.",
          "IoT integration so vitals from hardware flow into the same record instead of living in a separate app."
        ],
        "architecture": [
          "Next.js front-end, Supabase for auth and data, an AI layer for the symptom checker.",
          "Health records structured so a doctor can read them in seconds, not paragraphs."
        ],
        "stack": ["Next.js", "Supabase", "AI", "IoT"],
        "challenges": [
          {
            "problem": "Making the symptom checker useful without being reckless.",
            "fix": "Every answer is a triage suggestion with a clear disclaimer — the tool points you at the right kind of care, it never diagnoses."
          },
          {
            "problem": "Building it while juggling hackathons and a final-year project.",
            "fix": "Ship the core records + checker first; the emergency module and IoT hookups land in stages."
          }
        ],
        "impact": [
          "Digital health records in one place, connected to hardware where it counts.",
          "A symptom checker that redirects to real care instead of Dr. Google."
        ],
        "lessons": [
          "In healthcare the ceiling isn't technical, it's trust. Software that earns trust is built slower and carefully."
        ]
      },
      "links": {
        "github": "https://github.com/TheRowKneet68"
      }
    },
    {
      "id": "suraksha-ghar",
      "title": "SurakshaGhar",
      "tagline": "Home automation I actually shipped",
      "category": "IoT & Security",
      "year": "2024",
      "status": "shipped",
      "featured": true,
      "tech": [
        "ESP32",
        "ESP8266",
        "Firebase",
        "PCB Design",
        "Blynk"
      ],
      "description": "My home automation ecosystem — 4-channel relay switch, RFID door lock, PIR detection, web control and a companion app. I designed the PCB in EasyEDA, flashed the firmware, and took it from breadboard to production switch.",
      "highlights": [
        "Custom PCB (Gerber files)",
        "Companion mobile app",
        "Production 4-channel switch"
      ],
      "links": {
        "github": "https://github.com/TheRowKneet68"
      }
    },
    {
      "id": "swiftignite",
      "title": "SwiftIgnite",
      "tagline": "Keyless motorcycle ignition system",
      "category": "Automotive IoT",
      "year": "2025",
      "status": "v2 planned",
      "featured": true,
      "tech": [
        "nRF52840",
        "Neo-M8N GPS",
        "SIM800L",
        "HC-05",
        "BLE"
      ],
      "description": "Motorcycle keyless ignition — Bluetooth + relays + battery management in one board. Version 2 adds live GPS tracking, SIM800L telemetry and an SMS database so you always know where your bike is.",
      "highlights": [
        "Keyless ignition",
        "GPS live tracking (Neo-M8N)",
        "SMS alerts + DB logging"
      ],
      "caseStudy": {
        "problem": [
          "Motorcycle keys get lost, and ignitions get tampered with. Aftermarket security is either dumb — no tracking — or tied to GSM subscriptions you keep paying.",
          "A security upgrade that drains your battery while the bike sits is worse than no upgrade."
        ],
        "solution": [
          "Keyless ignition: a BLE connection from your phone, relay-controlled, with battery management in one board.",
          "V2 turns it into a full tracker — Neo-M8N GPS, SIM800L telemetry and an SMS database so you always know where the bike is."
        ],
        "architecture": [
          "nRF52840 handles BLE pairing and ignition control; relays switch the ignition line.",
          "Neo-M8N feeds GPS position, SIM800L provides cellular fallback so the bike can be located even without phone coverage."
        ],
        "stack": ["nRF52840", "Neo-M8N", "SIM800L", "BLE", "Relays"],
        "challenges": [
          {
            "problem": "Power. An ignition system can't drain a bike battery that sits for weeks.",
            "fix": "Deep-sleep states and proper battery management so idle draw stays in the microamp range."
          },
          {
            "problem": "A dead BLE connection shouldn't strand the rider.",
            "fix": "Kept a physical fallback path in the design — keyless should mean convenient, not risky."
          }
        ],
        "impact": [
          "Keyless ignition, live GPS tracking and SMS alerts in one board.",
          "V2 shipping with telemetry logging so theft recovery is a text message away."
        ],
        "lessons": [
          "The last 10% of a hardware project is power management, and it's the part that decides whether anyone actually uses it."
        ]
      },
      "links": {
        "github": "https://github.com/TheRowKneet68"
      }
    },
    {
      "id": "gravas",
      "title": "GRAVAS",
      "tagline": "Gesture-controlled robotic arm",
      "category": "Robotics",
      "year": "2025",
      "status": "major project",
      "featured": true,
      "tech": [
        "Python",
        "MediaPipe",
        "OpenCV",
        "Arduino",
        "Servos"
      ],
      "description": "My Bachelor's major project — a robotic arm that follows your hand using MediaPipe hand tracking. No gloves, no markers. Python reads your hand, pyFirmata moves the servos.",
      "highlights": [
        "MediaPipe hand tracking",
        "pyFirmata servo control",
        "Defended in front of a panel"
      ],
      "caseStudy": {
        "problem": [
          "Driving a robotic arm with a joystick is fine. Controlling it by pointing your hand at it is how you actually feel the robot.",
          "Most gesture arms need gloves or markers — gear that breaks the whole point of a natural interface."
        ],
        "solution": [
          "MediaPipe hand tracking reads your hand with the laptop camera — no gloves, no markers.",
          "Python maps the gesture to servo positions and pyFirmata moves the arm over serial."
        ],
        "architecture": [
          "OpenCV + MediaPipe detects the hand and computes landmarks; a gesture map converts them to target angles.",
          "Arduino runs the servo control loop, pyFirmata provides the protocol bridge."
        ],
        "stack": ["Python", "MediaPipe", "OpenCV", "Arduino", "Servos", "pyFirmata"],
        "challenges": [
          {
            "problem": "Latency. A laggy arm feels dead and kills the whole illusion.",
            "fix": "Downscaled frames and targeted landmark math to keep the control loop tight."
          },
          {
            "problem": "Defending it to a panel that knows how to ask hard questions.",
            "fix": "Documented every decision in the project proposal — the 'why' mattered more than the demo."
          }
        ],
        "impact": [
          "Defended in front of the panel as my Bachelor's major project.",
          "Proved the natural-interface stack I now reach for in vision projects."
        ],
        "lessons": [
          "Natural interfaces are a latency problem before they're a feature problem."
        ]
      },
      "links": {
        "github": "https://github.com/TheRowKneet68"
      }
    },
    {
      "id": "air-mouse",
      "title": "Air Mouse",
      "tagline": "Mouse controlled by pointing",
      "category": "Computer Vision",
      "year": "2022",
      "status": "award-winning",
      "featured": true,
      "tech": [
        "Arduino",
        "Sensors",
        "Python"
      ],
      "description": "One of my earliest projects — control the cursor by moving your hand in the air. Basically told me which direction I was going in.",
      "highlights": [],
      "links": {
        "github": "https://github.com/TheRowKneet68"
      }
    },
    {
      "id": "aegis",
      "title": "AEGIS",
      "tagline": "Disaster response ecosystem (concept)",
      "category": "Concept",
      "year": "2026",
      "status": "concept",
      "featured": false,
      "tech": [
        "Robots",
        "Drones",
        "Sensors",
        "AI",
        "Smart City"
      ],
      "description": "A large-scale disaster-response concept — smart city, robots, drones, sensors, AI and a central command center all talking to each other. The next thing I want to exist.",
      "highlights": [
        "Smart city integration",
        "Command & control center"
      ],
      "links": {}
    },
    {
      "id": "motor-control",
      "title": "Call-Based Motor Control",
      "tagline": "Turn motors on/off with a phone call",
      "category": "IoT & Security",
      "year": "2025",
      "status": "market-launched",
      "featured": false,
      "tech": [
        "ESP32",
        "GSM",
        "Relays"
      ],
      "description": "A product I took to market in May 2025 — control industrial/agricultural motors with a simple phone call. No internet needed, no app, no subscription. Built for places where WiFi doesn't reach.",
      "highlights": [
        "Launched to market — May 27, 2025",
        "Works without internet"
      ],
      "links": {}
    },
    {
      "id": "ghostware",
      "title": "Ghostware360: Debug or Die",
      "tagline": "Horror puzzle game, in progress",
      "category": "Game",
      "year": "2026",
      "status": "in progress",
      "featured": false,
      "tech": [
        "Game Dev",
        "Horror",
        "Puzzle"
      ],
      "description": "A horror-puzzle game where debugging is the gameplay. You're a developer trapped in a haunted codebase. Still being built — because who doesn't want to turn debugging into a horror story.",
      "highlights": [
        "Horror + coding theme"
      ],
      "links": {}
    },
    {
      "id": "smart-parking",
      "title": "Smart Parking System",
      "tagline": "Parking that tells you where to go",
      "category": "IoT & Security",
      "year": "2024",
      "status": "built",
      "featured": false,
      "tech": [
        "ESP32",
        "Sensors",
        "IoT"
      ],
      "description": "IoT parking system — sensors detect free slots and point drivers to them instead of circling forever.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "stealth-rc",
      "title": "RC Car Builds",
      "tagline": "Rc_Car1, Rc_Car2 & the NRF stealth version",
      "category": "Robotics",
      "year": "2023",
      "status": "built",
      "featured": false,
      "tech": [
        "Arduino",
        "NRF",
        "Motors"
      ],
      "description": "A whole garage of RC cars — Rc_Car1 and Rc_Car2 plus a stealth variant that swapped IR for NRF radio modules, so it actually works outside the living room.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "gps-buck",
      "title": "GPS Tracker & Buck Converter",
      "tagline": "Track a thing, power it properly",
      "category": "Hardware",
      "year": "2024",
      "status": "built",
      "featured": false,
      "tech": [
        "GPS",
        "Buck Converter",
        "Power Electronics"
      ],
      "description": "Two-in-one hardware exercise — a working GPS tracker plus a custom buck converter to power it from a battery properly.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "lyrics-display",
      "title": "Lyrics Display Systems",
      "tagline": "OLED & LCD lyric players",
      "category": "Electronics",
      "year": "2026",
      "status": "fun",
      "featured": false,
      "tech": [
        "ESP32",
        "OLED",
        "LCD I2C",
        "Internet"
      ],
      "description": "A whole series of lyric display builds — OLED and LCD boards that fetch song lyrics from the internet and scroll them in real time. Music on hardware. Ten-plus songs, ten-plus variants.",
      "highlights": [
        "SMART_INTERNET_LYRICS_DISPLAY_SYSTEM",
        "10+ song variants"
      ],
      "links": {}
    },
    {
      "id": "fishtail",
      "title": "Fishtail",
      "tagline": "Dev-core + hardware workspace",
      "category": "Hardware",
      "year": "2026",
      "status": "experimental",
      "featured": false,
      "tech": [
        "ESP-IDF",
        "C",
        "Hardware"
      ],
      "description": "My experimental workspace — a mix of dev-core software and raw hardware experiments. The drawer where projects start before they get names.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "mama",
      "title": "M.A.M.A",
      "tagline": "Multi-Agency Management Assistant",
      "category": "Software",
      "year": "2024",
      "status": "prototype",
      "featured": false,
      "tech": [
        "Web",
        "Prototype"
      ],
      "description": "Concept + prototype for a multi-agency management assistant — one dashboard for agencies that never talk to each other.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "herlegal",
      "title": "HerLegal",
      "tagline": "Legal resource site",
      "category": "Web",
      "year": "2024",
      "status": "built",
      "featured": false,
      "tech": [
        "HTML",
        "Supabase",
        "CSS"
      ],
      "description": "A legal information site — static front-end with Supabase for content. Early web work while I was learning how the other half of software lives.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "qr-tool",
      "title": "Bulk QR Generator",
      "tagline": "Hundreds of QR codes, one script",
      "category": "Tools",
      "year": "2026",
      "status": "tool",
      "featured": false,
      "tech": [
        "Python"
      ],
      "description": "A Python tool that turns a CSV into hundreds of QR codes in one run. Built because I needed it, the way all good tools get built.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "rudra",
      "title": "RUDRA-1",
      "tagline": "Camera-based robotics project",
      "category": "Robotics",
      "year": "2025",
      "status": "completed",
      "featured": false,
      "tech": [
        "Computer Vision",
        "Robotics"
      ],
      "description": "A robotics project built around cameras and vision, complete with full project proposal documentation. Won the 9th PEC Tech Expo.",
      "highlights": [
        "Winner — 9th PEC Tech Expo"
      ],
      "links": {}
    },
    {
      "id": "airis",
      "title": "A.I.R.I.S.",
      "tagline": "Personal voice assistant",
      "category": "AI & Health",
      "year": "2026",
      "status": "built",
      "featured": false,
      "tech": [
        "Python",
        "Speech-to-Text",
        "TTS"
      ],
      "description": "My own voice assistant — speech-to-text, text-to-speech, command handling, all wired together locally. Half product, half training my Python.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "rubber-ducky",
      "title": "USB Rubber Ducky builds",
      "tagline": "Keystroke injection experiments",
      "category": "Security",
      "year": "2026",
      "status": "experimental",
      "featured": false,
      "tech": [
        "USB HID",
        "Security"
      ],
      "description": "USB keystroke-injection experiments with a Rubber Ducky. Security research — knowing how these work is how you defend against them.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "smart-dustbin",
      "title": "SmartDustBin",
      "tagline": "A dustbin with a brain",
      "category": "IoT & Security",
      "year": "2023",
      "status": "built",
      "featured": false,
      "tech": ["ESP32", "Sensors"],
      "description": "A smart dustbin firmware — sensors and automation so the bin handles itself. Small project, big lesson in keeping things simple.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "slide-smart",
      "title": "SlideSmart",
      "tagline": "Mobile-controlled curtain automation",
      "category": "IoT & Security",
      "year": "2024",
      "status": "built",
      "featured": false,
      "tech": ["ESP32", "Mobile", "Relays"],
      "description": "Curtain automation you drive from your phone. Press a button, curtains slide. The boring problems are the ones worth automating.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "custom-buck",
      "title": "Custom Buck Converter",
      "tagline": "Down-voltage, my way",
      "category": "Hardware",
      "year": "2024",
      "status": "built",
      "featured": false,
      "tech": ["Power Electronics", "LM2596"],
      "description": "A custom buck converter I designed — dropping battery voltage down cleanly for the boards that need it. Power electronics is where projects live or die.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "custom-relay",
      "title": "Custom Relay Module",
      "tagline": "Relay board, designed from scratch",
      "category": "Hardware",
      "year": "2024",
      "status": "built",
      "featured": false,
      "tech": ["Relays", "PCB Design"],
      "description": "A relay module I designed myself rather than buying off the shelf — the kind of component that shows up in half my other projects.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "earthquake-sim",
      "title": "Earthquake Simulator",
      "tagline": "Python/Flask app that shakes",
      "category": "Software",
      "year": "2026",
      "status": "built",
      "featured": false,
      "tech": ["Python", "Flask", "Web"],
      "description": "A Flask app that visualizes earthquakes — plotting the ones that already happened and simulating the ones that might. Web + Python in one project.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "mass-report",
      "title": "Mass Report (TikTok Bot)",
      "tagline": "Automation for a reason",
      "category": "Tools",
      "year": "2026",
      "status": "tool",
      "featured": false,
      "tech": ["Python", "Automation"],
      "description": "A Python reporting bot that handles mass reporting on TikTok. Built to automate something that was taking hours by hand.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "home-auto-lab",
      "title": "Home Automation Lab",
      "tagline": "ESP32 experiments: LDR, ultrasonic, relays",
      "category": "IoT & Security",
      "year": "2023",
      "status": "experimental",
      "featured": false,
      "tech": ["ESP32", "LDR", "Ultrasonic", "Relays"],
      "description": "My self-hosted home-automation lab — light sensors, ultrasonic triggers, relay boards and ESP32 wroom modules. The sandbox where home automation got figured out.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "wifi-tracking",
      "title": "WiFi Tracking & CSI",
      "tagline": "RuView + channel-state experiments",
      "category": "Security",
      "year": "2026",
      "status": "experimental",
      "featured": false,
      "tech": ["WiFi", "ESP32", "CSI"],
      "description": "WiFi tracking experiments — RuView for device detection and channel-state-information capture to understand what WiFi can see. A deep rabbit hole.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "esp-toolkit",
      "title": "ESP Utility Toolkit",
      "tagline": "MAC finder, pin checker, tag victim",
      "category": "Hardware",
      "year": "2026",
      "status": "tool",
      "featured": false,
      "tech": ["ESP32", "ESP8266", "nRF52840"],
      "description": "A pile of small but essential ESP utilities — finding MAC addresses, checking pin layouts on nRF boards, and a Lager Tag victim build. The unglamorous tools every build depends on.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "room-light",
      "title": "RoomLightApp",
      "tagline": "Room lighting from your pocket",
      "category": "Software",
      "year": "2023",
      "status": "built",
      "featured": false,
      "tech": ["App", "IoT"],
      "description": "A room-light control app — early attempt at putting my hardware behind a phone interface.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "ctevt-checker",
      "title": "Diploma CTEVT Checker",
      "tagline": "Result checker desktop app",
      "category": "Tools",
      "year": "2024",
      "status": "shipped",
      "featured": false,
      "tech": ["Python", "PyInstaller", "Desktop"],
      "description": "A desktop app that checks Diploma CTEVT results — packaged into a real .exe with PyInstaller so batch-mates could run it without touching Python.",
      "highlights": ["Packaged .exe", "Built for batch-mates"],
      "links": {}
    },
    {
      "id": "restaurant-websites",
      "title": "Restaurant Websites (ROS)",
      "tagline": "Butter Mellow, Ember & Ivy, Nako Cafe & more",
      "category": "Web",
      "year": "2025",
      "status": "freelance",
      "featured": false,
      "tech": ["Next.js", "Prisma", "Supabase"],
      "description": "A string of restaurant websites I designed, built and deployed — Butter Mellow Cafe, Ember & Ivy, Foxy's Corner, Nako Cafe Lakeside, Newari Bhatti and a few others. This is also where I learned cold outreach: message a restaurant, build them a site, iterate on the pitch until one says yes.",
      "highlights": ["Multiple live restaurant sites", "Cold-outreach workflow"],
      "links": {}
    },
    {
      "id": "pahilo-mart",
      "title": "PahiloMart WebPage",
      "tagline": "Vite + TypeScript storefront",
      "category": "Web",
      "year": "2026",
      "status": "built",
      "featured": false,
      "tech": ["Vite", "TypeScript", "Tailwind"],
      "description": "A web-store landing page built with Vite + TypeScript + Tailwind and deployed behind Netlify redirects. Modern front-end stack, real product intent.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "group-minor-project",
      "title": "Group Minor Project (PHP)",
      "tagline": "Login/signup system",
      "category": "Web",
      "year": "2023",
      "status": "academic",
      "featured": false,
      "tech": ["PHP", "MySQL", "CSS"],
      "description": "College group project — a PHP login/signup system running on XAMPP. My first taste of auth, sessions and why the back-end hurts.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "n8n-selfhost",
      "title": "Self-Hosted n8n",
      "tagline": "Workflow automation, my own server",
      "category": "Software",
      "year": "2026",
      "status": "tool",
      "featured": false,
      "tech": ["n8n", "Docker", "Automation"],
      "description": "n8n self-hosted in Docker — my own workflow automation server. I like owning the tools I depend on.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "home-motor-timer",
      "title": "Home Motor Timer",
      "tagline": "Motor on for 6 hrs, off for 1 min, repeat",
      "category": "IoT & Security",
      "year": "2024",
      "status": "built",
      "featured": false,
      "tech": ["Relays", "Timing", "Electronics"],
      "description": "A real-world household problem solved — a timer that runs a home motor on a strict cycle so it never burns itself out. Built because home needed it.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "ai-agents",
      "title": "AI Agents & Hand Detection",
      "tagline": "REAL_AGENT, AI AGENT & vision demos",
      "category": "AI & Health",
      "year": "2026",
      "status": "experimental",
      "featured": false,
      "tech": ["Python", "AI", "OpenCV", "MediaPipe"],
      "description": "An experimental stack — REAL_AGENT and AI AGENT scripts plus hand-detection demos. The AI/vision layer of what becomes bigger things.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "java-practical",
      "title": "JAVA Practical",
      "tagline": "Semester Java practice",
      "category": "Academic",
      "year": "2026",
      "status": "academic",
      "featured": false,
      "tech": ["Java"],
      "description": "My semester Java practical work — the theory-heavy half of engineering. I learn better with a soldering iron, but Java got drilled in anyway.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "espidf-hello",
      "title": "ESP-IDF Hello World",
      "tagline": "Day 01 / Test / hello_world experiments",
      "category": "Academic",
      "year": "2026",
      "status": "academic",
      "featured": false,
      "tech": ["ESP-IDF", "C", "CMake"],
      "description": "The very first ESP-IDF experiments — Day 01, Test, hello_world — with CMake, sdkconfig and a pytest hello-world test. Every big project starts with a blinking LED.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "web-clones",
      "title": "Cloned & Scraped Websites",
      "tagline": "royevent.com, GandakiTent, SlayerCloudSite & more",
      "category": "Academic",
      "year": "2024",
      "status": "academic",
      "featured": false,
      "tech": ["HTML", "Scraping", "CSS"],
      "description": "A folder of cloned and scraped sites — royevent.com, Gandaki Tent & Decoration, sagarmathapokhara.edu.np, SlayerCloudSite and saved pages from box.com, dropbox, icloud and google. How I reverse-engineered websites before I could build my own.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "d-app",
      "title": "D:\\app — Next.js App",
      "tagline": "App router experiments",
      "category": "Academic",
      "year": "2025",
      "status": "academic",
      "featured": false,
      "tech": ["Next.js", "React", "TypeScript"],
      "description": "A bare Next.js app — layout, page, not-found and globals. Early experiments with the App Router that later grew into real sites.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "computer-graphics",
      "title": "Computer Graphics",
      "tagline": "Semester graphics course work",
      "category": "Academic",
      "year": "2025",
      "status": "academic",
      "featured": false,
      "tech": ["Graphics", "C"],
      "description": "Semester computer graphics work — the math and code behind rendering things to a screen.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "assembly-coding",
      "title": "Assembly Level Coding",
      "tagline": "Talking to the metal",
      "category": "Academic",
      "year": "2025",
      "status": "academic",
      "featured": false,
      "tech": ["Assembly", "VHDL"],
      "description": "Assembly-level programming and VHDL coursework — getting down to where the processor actually lives. Painful, educational, useful once.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "project05-pa",
      "title": "Project05 PA",
      "tagline": "Home-lab mini project",
      "category": "Academic",
      "year": "2024",
      "status": "academic",
      "featured": false,
      "tech": ["Electronics"],
      "description": "One of my home-lab mini projects — the kind of thing I built on the workbench between real projects.",
      "highlights": [],
      "links": {}
    },
    {
      "id": "college-semesters",
      "title": "College Semesters (PEC)",
      "tagline": "BE.PEC & PEC semester folders",
      "category": "Academic",
      "year": "2024",
      "status": "academic",
      "featured": false,
      "tech": ["Theory", "Presentations"],
      "description": "The full BE college archive — semester folders from BE.PEC and PEC with notes, presentations and exam prep. The paperwork side of engineering.",
      "highlights": [],
      "links": {}
    }
  ],
  "achievements": [
    {
      "id": "pec-tech-expo-2022",
      "event": "PEC Tech Expo 2022",
      "title": "RUDRA-1 & Suraksha360",
      "year": "2022",
      "result": "1st Place",
      "detail": "Won with RUDRA-1 — camera-based robotics, and Suraksha360 — smart security. First taste of what building weird things gets you."
    },
    {
      "id": "gces-it-expo-2024",
      "event": "GCES IT Expo 2024",
      "title": "Suraksha360",
      "year": "2024",
      "result": "1st Place",
      "detail": "Took Suraksha360 to the 11th GCES IT Expo and won."
    },
    {
      "id": "surakshaghar-shipped",
      "event": "SurakshaGhar",
      "title": "Home automation ecosystem",
      "year": "2024",
      "result": "Shipped",
      "detail": "Home automation ecosystem — 4-channel relay switch, RFID door lock, PIR detection, web control and a companion app. Custom PCB designed in EasyEDA, from breadboard to production switch."
    },
    {
      "id": "udaan-2025",
      "event": "UDAAN 2025 — Project Expo (IOE Paschimanchal Campus, WRC)",
      "title": "Suraksha360",
      "year": "2025",
      "result": "Winner",
      "detail": "7 Feb 2025 — Won the UDAAN 2025 Project Expo with Suraksha360."
    },
    {
      "id": "udaan-2025-participant",
      "event": "UDAAN 2025 Project Expo",
      "title": "Participant",
      "year": "2025",
      "result": "Certificate of Appreciation",
      "detail": "7 Feb 2025 — Certificate of Appreciation for participation."
    },
    {
      "id": "octate-2025",
      "event": "OCTATE 2025 — National Level Technical Festival",
      "title": "Suraksha360",
      "year": "2025",
      "result": "People's Choice Award",
      "detail": "12–13 Feb 2025 — Won the People's Choice / Public Choice Award at the OCTATE 2025 National Level Technical Festival."
    },
    {
      "id": "innosphere-1",
      "event": "Innosphere 1.0 — Hardware Project Exhibition",
      "title": "Suraksha360",
      "year": "2025",
      "result": "First Runner-Up",
      "detail": "8 Jun 2025 — First Runner-Up at the Innosphere 1.0 Hardware Project Exhibition."
    },
    {
      "id": "hackathon-nova-partner",
      "event": "Hackathon Nova",
      "title": "Suraksha Ghar — Community Partner",
      "year": "2025",
      "result": "Community Partner",
      "detail": "Certificate of Appreciation as Community Partner (Suraksha Ghar)."
    },
    {
      "id": "hackathon-nova-volunteer",
      "event": "Hackathon Nova",
      "title": "Volunteer",
      "year": "2025",
      "result": "Volunteer",
      "detail": "Certificate of Appreciation as Volunteer."
    },
    {
      "id": "capec-leadership",
      "event": "CAPEC",
      "title": "Leadership & Dedication",
      "year": "2025",
      "result": "Appreciation",
      "detail": "Certificate of Appreciation for leadership and dedication as a member (2024–2025 tenure)."
    },
    {
      "id": "swiftignite",
      "event": "SwiftIgnite",
      "title": "Keyless motorcycle ignition",
      "year": "2025",
      "result": "v2 planned",
      "detail": "Keyless motorcycle ignition — Bluetooth + relays + battery management in one board. V2 adds live GPS tracking, SIM800L telemetry and an SMS database."
    },
    {
      "id": "call-motor-control",
      "event": "Call-Based Smart Motor Control",
      "title": "Market-launched",
      "year": "2025",
      "result": "Market-launched",
      "detail": "Launched to market 27 May 2025 — control industrial and agricultural motors with a phone call. No internet needed, no app, no subscription."
    },
    {
      "id": "capec-joint-secretary",
      "event": "CAPEC",
      "title": "Joint Secretary, 2026",
      "year": "2026",
      "result": "Appointed",
      "detail": "26 Dec 2025 — Official appointment as Joint Secretary of CAPEC for 2026."
    },
    {
      "id": "pec-2026-civil",
      "event": "9th PEC Tech Expo 2026 — Civil Project Competition",
      "title": "Suraksha360",
      "year": "2026",
      "result": "First Runner-Up",
      "detail": "28–29 Jan 2026 — First Runner-Up in the Civil Project Competition."
    },
    {
      "id": "pec-2026-it",
      "event": "9th PEC Tech Expo 2026 — Computer & IT Project Competition",
      "title": "Suraksha360",
      "year": "2026",
      "result": "Consolation",
      "detail": "28–29 Jan 2026 — Consolation prize in the Computer & IT Project Competition."
    },
    {
      "id": "pec-2026-participants",
      "event": "9th PEC Tech Expo 2026",
      "title": "Participant — multiple projects",
      "year": "2026",
      "result": "Participant",
      "detail": "28–29 Jan 2026 — Participation certificates: Construction of Roundabout with Pedestrian Bridge at Prithvichowk, HerLegal, Surakshya 360, Suraksha360, Rudra 1, RUDRA-I, and Laser Tag."
    },
    {
      "id": "fishtail-fair-2026",
      "event": "Fishtail University Fair",
      "title": "Suraksha360",
      "year": "2026",
      "result": "Presented",
      "detail": "4 Apr 2026 — Presented Suraksha360 to students, faculty, and industry visitors, demonstrating practical IoT, automation, and embedded system solutions."
    },
    {
      "id": "codefest-2026",
      "event": "Codefest 2026 — Gandaki Province",
      "title": "Team Suraksha360",
      "year": "2026",
      "result": "Participated",
      "detail": "Jul 2026 — Team Suraksha360 participated in the Codefest 2026 Gandaki province hackathon."
    },
    {
      "id": "gces-it-expo-2026",
      "event": "GCES IT Expo 2026",
      "title": "Suraksha360",
      "year": "2026",
      "result": "1st Position",
      "detail": "25–26 Jun 2026 — Suraksha360 earned First Place at the GCES IT Expo, recognizing months of engineering, iteration, and real-world product development."
    }
  ]
};
