/* Regenerate server/data.embedded.ts from data.json so the API function can
   bundle content without JSON-import syntax (which not every bundler parses).
   Run: npm run sync:data  (runs automatically as part of `npm run build`) */
import { readFileSync, writeFileSync } from "node:fs";

const raw = readFileSync("data.json", "utf8");
JSON.parse(raw); // fail loudly if data.json is malformed

const out =
  "// GENERATED by scripts/sync-data.mjs from data.json — do not edit by hand.\n" +
  "// Rebuild with `npm run sync:data`.\n" +
  `export const EMBEDDED_DATA = ${raw};\n`;

writeFileSync("server/data.embedded.ts", out);
console.log(`wrote server/data.embedded.ts (${out.length} bytes)`);
